### ISSUE TITLE
Want to become main maintainer for this repo?

### ISSUE THREAD

**Issue by x80486** [flathub/com.jetbrains.IntelliJ-IDEA-Community#103]
If you are reading this, actively use `IntelliJ IDEA Community`, and interested on being the **main maintainer** for this repo, I'll gladly hand it over to you. Let me know via e-mail or just by chiming in.

> I will stop using `IntelliJ IDEA Community` any time soon, that's why I would like to hand this over. In any case, I'll keep maintain it until somebody else is interested.

**Comment by Eonfge** [comment]
Oof, this is a hard call because as it stands, I already maintain multiple applications and I don't know if I can take another project.

**Comment by xanscale** [comment]
@x80486 hi, i'm the mantainer of android studio flatpak wrapper i can help to mantain this repo (and ultimate)

**Comment by x80486** [comment]
@barthalion, could you add Alessandro as main maintainer for this package?
