### ISSUE TITLE
Signing Commits via GPG doesn't work

### ISSUE THREAD

**Issue by tunix** [flathub/com.jetbrains.IntelliJ-IDEA-Community#122]
Hi,

I'm trying to create a consistent setup for GPG signing on CLI and IDE (Intellij Idea Community Edition). So far, I'm able to sign my commits with CLI on host, toolbox containers and the terminal inside the IDE but not the IDE itself. I mean, if I use the built-in git capabilities of the IDE, it will simply fail with the following error:

```
error: gpg failed to sign the data
fatal: failed to write commit object
```

I have Fedora Silverblue 37 on my laptop and here are my configs:

#### .gitconfig
```
[user]
    signingkey = 476B3D9B8D36FDE6!
[commit]
    gpgsign = true
```

#### gpg.conf
```
use-agent
keyserver hkps://keys.openpgp.org
pinentry-mode loopback
```

#### gpg-agent.conf
```
default-cache-ttl 600
max-cache-ttl 7200
pinentry-program /usr/bin/pinentry
```

The flatpak Intellij Idea Community includes pinentry-gnome3 bundled and when I type `gpgconf` in its terminal, I get the following output:

```
$ gpgconf
gpg:OpenPGP:/usr/bin/gpg
gpgsm:S/MIME:/usr/bin/gpgsm
gpg-agent:Private Keys:/usr/bin/gpg-agent
scdaemon:Smartcards:/usr/libexec/scdaemon
dirmngr:Network:/usr/bin/dirmngr
pinentry:Passphrase Entry:/usr/bin/pinentry
```

I'm able to use pinentry inside the terminal of the IDE:

```
$ echo getpin|pinentry
OK Pleased to meet you
D asd
OK
```

gpg-agent is running on the host and if I let it cache the password of my GPG key, I'm able to sign commits both on the host and inside the IDE without any issues. So the problem seems to be that the IDE is not able to ask for the GPG password.

I tried various configurations like setting `pinentry-mode ask`, adding `no-tty` option etc but none of those actually worked. I also gave `gpg-agent` socket permission to the IDE but that didn't work as well.

What am I missing? Does anyone have an idea about this?

More Information about my system:

#### gpg inside container
```
$ gpg --version
gpg (GnuPG) 2.2.39
libgcrypt 1.10.1
Copyright (C) 2022 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /var/home/tunix/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by x80486** [comment]
Let me take a look at this one. Just a quick workaround: what happens if you start the application using the CLI: `flatpak run com.jetbrains.IntelliJ-IDEA-Community`?

**Comment by tunix** [comment]
> Let me take a look at this one. Just a quick workaround: what happens if you start the application using the CLI: `flatpak run com.jetbrains.IntelliJ-IDEA-Community`?

Unfortunetely the problem still persists. I don't see any related logs as well.

**Comment by x80486** [comment]
OK, I understand now. You are trying to use the built-in `Git` plugin from `IDEA`, right? If that's the case, it's going to be a little bit of a challenge, because I don't know how that works internally.

Let me try to give it a whirl, but I guess this is one of those cases where a proper integration is needed between the application and the (Flatpak) bundle :crossed_fingers:

**Comment by tunix** [comment]
> OK, I understand now. You are trying to use the built-in `Git` plugin from `IDEA`, right? If that's the case, it's going to be a little bit of a challenge, because I don't know how that works internally.
> 
> Let me try to give it a whirl, but I guess this is one of those cases where a proper integration is needed between the application and the (Flatpak) bundle crossed_fingers

Yes, I'm trying to use the built-in `git` plugin from `IDEA`. If needed, I may create an issue in their tracker as well. Please let me know if I can do anything else.

**Comment by x80486** [comment]
I gave it another whirl to this but the plugin is not quite behaving as one might expect, in terms of completely interacting with the host's `Git` install.

I don't think it should be horribly difficult to support this because there are other applications (`SmartGit`, for instance) in the same realm that already behave correctly, though they might have taken a different approach internally — and that could be a game changer.

Feel free to open an issue in `YouTrack`; please refer to the same here. The only reason I'm asking (instead of doing it myself) is because you are going to have more details on your end.

**Comment by tunix** [comment]
Looks like an issue is already created by others: https://youtrack.jetbrains.com/issue/IDEA-249376/Cannot-GPG-sign-a-commit-with-the-flatpak-version-of-Intellij

**Comment by x80486** [comment]
It's in the `PATH`, regardless. I can do that small change and push a branch to see if that works for you.

Feel free to send a pull request with the changes as well. Instructions to build the `Flatpak` locally are on the `README` :raised_hands:

**Comment by x80486** [comment]
If I try to do that, I get this error:

```shell
Running: ln --symbolic /app/bin/pinentry /usr/bin/pinentry
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/idea --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/idea-1 --bind-mount=/run/build/idea=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/idea-1 --build-dir=/run/build/idea --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1688959044 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/rofiles/rofiles-7ED7wi /bin/sh -c 'ln --symbolic /app/bin/pinentry /usr/bin/pinentry'' on host
ln: failed to create symbolic link '/usr/bin/pinentry': Read-only file system
FB: host_command_exited_cb 2568592 256
]2;flatpak-builder: Cleanup ideaError: module idea: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/rofiles/rofiles-7ED7wi
program finished with exit code 1
elapsedTime=151.395984
```

I'm not entirely sure if there is another way to do this, but just adding `ln --symbolic /app/bin/pinentry /usr/bin/pinentry` in the _idea_ dependency doesn't work.

**Comment by x80486** [comment]
@tunix, can you update to the latest version and see if this issue is resolved on your end?

**Comment by Ombrelin** [comment]
Hi @x80486 ,
I just got the same exact problem : 

<img width="1915" height="621" alt="Image" src="https://github.com/user-attachments/assets/60d9b80e-731b-4eb4-a1a4-a52d161462ae" />

Maybe the regression is related to the changes from 2025.3 ?
Thanks in advance,
