### ISSUE TITLE
After upgrade to 2023.1 IntelliJ crashes at start up

### ISSUE THREAD

**Issue by bjornbak** [flathub/com.jetbrains.IntelliJ-IDEA-Community#124]
I just received the upgrade to 2023.1 but after upgrading IntelliJ crashes at start up.

When started from console with: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=idea com.jetbrains.IntelliJ-IDEA-Community` I get some logs written in the console.

Last line printed is:
```
[0329/073500.004250:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/idea-IC/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
```
but it continues another 10-15 secs scanning my open project before it crashes.

I tried to fix the error with 
```
sudo chmod 4755 /var/lib/flatpak/app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable/88eb...0a499/files/idea-IC/jbr/lib/chrome-sandbox
```
but it neither fixes the error message or the crash.

How do I fix? Or where should I look for the true cause of the crash?

**Comment by shijir38** [comment]
I'm also facing the same problem.


reason: 
`java killed by SIGTRAP`

cmdline:
`/app/idea-IC/jbr/bin/java -classpath /app/idea-IC/lib/app.jar:/app/idea-IC/lib/3rd-party-rt.jar:/app/idea-IC/lib/util.jar:/app/idea-IC/lib/util_rt.jar:/app/idea-IC/lib/util-8.jar:/app/idea-IC/lib/jps-model.jar:/app/idea-IC/lib/stats.jar:/app/idea-IC/lib/protobuf.jar:/app/idea-IC/lib/external-system-rt.jar:/app/idea-IC/lib/intellij-test-discovery.jar:/app/idea-IC/lib/forms_rt.jar:/app/idea-IC/lib/rd.jar:/app/idea-IC/lib/externalProcess-rt.jar:/app/idea-IC/lib/annotations-java5.jar:/app/idea-IC/lib/annotations.jar:/app/idea-IC/lib/byte-buddy-agent.jar:/app/idea-IC/lib/error-prone-annotations.jar:/app/idea-IC/lib/groovy.jar:/app/idea-IC/lib/idea_rt.jar:/app/idea-IC/lib/intellij-coverage-agent-1.0.706.jar:/app/idea-IC/lib/jsch-agent.jar:/app/idea-IC/lib/junit.jar:/app/idea-IC/lib/junit4.jar:/app/idea-IC/lib/ant/lib/ant.jar -XX:ErrorFile=/home/shijir/java_error_in_idea_%p.log -XX:HeapDumpPath=/home/shijir/java_error_in_idea_.hprof -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+IgnoreUnrecognizedVMOptions -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend -ea -Dsun.io.useCanonCaches=false -Dsun.java2d.metal=true -Djbr.catch.SIGABRT=true $'-Djdk.http.auth.tunneling.disabledSchemes=""' -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -Dsun.tools.attach.tmp.only=true -Xmx1962m -Djb.vmOptionsFile=/home/shijir/.var/app/com.jetbrains.IntelliJ-IDEA-Community/config/JetBrains/IdeaIC2023.1/idea64.vmoptions -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader -Didea.vendor.name=JetBrains -Didea.paths.selector=IdeaIC2023.1 -Djna.boot.library.path=/app/idea-IC/lib/jna/amd64 -Dpty4j.preferred.native.folder=/app/idea-IC/lib/pty4j -Djna.nosys=true -Djna.noclasspath=true -Didea.platform.prefix=Idea -Dsplash=true --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.dnd.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.event=ALL-UNNAMED --add-opens=java.desktop/java.awt.image=ALL-UNNAMED --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED --add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.desktop/sun.font=ALL-UNNAMED --add-opens=java.desktop/sun.java2d=ALL-UNNAMED --add-opens=java.desktop/sun.swing=ALL-UNNAMED --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED com.intellij.idea.Main `

**Comment by KevinAtSesam** [comment]
Can confirm.
```
[kevin@fedora ~]$ flatpak run com.jetbrains.IntelliJ-IDEA-Community 
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Gtk-Message: 08:52:40.220: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:52:40.220: Failed to load module "pk-gtk-module"
Gtk-Message: 08:52:40.220: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:52:40.220: Failed to load module "pk-gtk-module"
2023-03-29 08:52:40,604 [    615]   WARN - #c.i.o.v.n.p.l.VfsLog - VFS Log version differs from the implementation version: log null vs implementation -43
2023-03-29 08:52:40,950 [    961]   WARN - #c.i.o.a.i.ActionManagerImpl - keymap "VSCode" not found PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=/app/idea-IC/plugins/terminal, version=231.8109.175, package=null, isBundled=true)
2023-03-29 08:52:41,846 [   1857]   WARN - #c.j.p.PluginClassPathRuntimeCustomizer - There was more than one class loaded in Projector Plugin classloader - this is likely a bug!
2023-03-29 08:52:42,878 [   2889]   WARN - #c.i.o.w.i.s.w.StatusBarWidgetsManager - org.jetbrains.plugins.scala.components.TypeAwareWidgetFactory doesn't define id for extension (point=com.intellij.statusBarWidgetFactory). Please specify `id` attribute.
[0329/085245.799898:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/idea-IC/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
```

### Triage
How to continue using the older version:
```
sudo flatpak update --commit=7d6bf5632e6166a09b9d7fa606d91267fc38df839927af6754fb0b51bab6b81f com.jetbrains.IntelliJ-IDEA-Community
sudo flatpak mask com.jetbrains.IntelliJ-IDEA-Community
```

Don't forget that once this issue is resolved, to removethe mask again

```
sudo flatpak mask --remove com.jetbrains.IntelliJ-IDEA-Community
```

**Comment by x80486** [comment]
I think this is caused by a plugin you have installed. I did install the build from the merge request and everything was fine. I did it again now directly from `Flathub`'s release and it works.

![image](https://user-images.githubusercontent.com/34633617/228548850-d650ee01-6bb1-4b2d-a253-a18864183e77.png)

![image](https://user-images.githubusercontent.com/34633617/228549524-fde65dc5-0b30-4713-9052-cab1cfd48e0e.png)

Could you confirm if you are upgrading or installing from scratch? I would assume you are upgrading because I'm not facing the same problem(s); if that's the case, can you post the non-default plugins you have installed?

Additionally, you could also install from scratch just to test on your end as well.

**Comment by lkoning** [comment]
![image](https://user-images.githubusercontent.com/3646041/228571616-328214c4-661c-4ad6-a356-9bad7e62bd98.png)

Nothing fancy I think. Don't want to try to start from scratch.

**Comment by bjornbak** [comment]
I think what breaks upgrading is from the changelog:

Earlier availability of IDE features on project opening

We’ve improved the IDE startup experience by performing the Scanning files to index process in smart mode. Doing so makes the IDE’s full functionality available much earlier in the startup process. When opening a project, IntelliJ IDEA 2023.1 uses existing caches from your previous session with the project and simultaneously looks for files to index. If no changes are found in the scan, the IDE will be ready, eliminating the delays that were previously caused by indexing on startup.

**Comment by DottoXD** [comment]
Same issue here with both Visual Studio Code and IntelliJ IDEA after the latest update.

**Comment by allinkdev** [comment]
Can reproduce as well with the latest update, on Fedora Silverblue. Causes the entire system to freeze for a few seconds as well.

**Comment by sartrebrasil** [comment]
Hi guys, I managed to solve a similar problem after finding this [workaround] (https://youtrack.jetbrains.com/issue/IDEA-313202/chrome-sandbox-crashes-permission-not-set-correctly-after-update?s=chrome-sandbox-crashes-permission-not-set-correctly-after-update)

**Comment by Eonfge** [comment]
When I published my triage last week, I was in a bit of a hurry. Now looking at it again, there is another way to get Intellij running.

### Roll-back triage
```
sudo flatpak mask --remove com.jetbrains.IntelliJ-IDEA-Community
```

### factory-reset intellij
```
rm -rf ~/.var/app/com.jetbrains.IntelliJ-IDEA-Community
```

Not very elegant but it works

**Comment by shijir38** [comment]
> 
It worked! Thanks.
I was in a bit of a hurry too, should have removed application files first and tried again.

**Comment by FakeShemp** [comment]
The new Chromium sandbox needs zypak. See here for fix: https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534

**Comment by brittyazel** [comment]
Yep, I too had this issue and @deenie's fix worked to get me up and running. Disabling the sandbox for the integrated browser seemed to do the trick. Incorporating Zypak seems like the way to go to solve this outright.

**Comment by jurf** [comment]
You can also avoid opening the last project with a `flatpak run com.jetbrains.IntelliJ-IDEA-Community dontReopenProjects`.

**Comment by bademux** [comment]
Looks like "zypak" thing breaks  Idea https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534#issuecomment-1501811242

**Comment by brittyazel** [comment]
Is this fixed? I saw you rolled  back the Zypak commit, so this issue is valid again right?
