### ISSUE TITLE
No access to /bin makes the integrated terminal useless

### ISSUE THREAD

**Issue by ghost** [flathub/com.jetbrains.IntelliJ-IDEA-Community#14]
Hello,
I hope this is the right place to ask.

It would be useful to have access to `/bin` to execute commands from the integrated terminal.
Since `/bin` [is blacklisted](http://docs.flatpak.org/en/latest/sandbox-permissions.html) I'm not sure if this is even possible.
`flatpak override` does not seem to work for me.

Is this by design or can this be changed?

**Comment by x80486** [comment]
Indeed, the integrated terminal is somehow limited when using the Flatpak. I've tried also `flatpak override` but it doesn't quite work...so in the end I use the operating system's `Terminal` :sunglasses: 

I don't think there is anything actionable on my end here, it's the way it works – or at least that's what I understand from my limited knowledge about Flatpaks in general.

**Comment by Marteon** [comment]
I'll do some more research to probably fix this.
Are you fine with leaving this issue opened until we surely know why/if this cannot be solved?

**Comment by TingPing** [comment]
You fix this by getting a job at JetBrains and spend months redesigning the core of the editor to understand commands executing in different environments.

In the mean time you either:

- Package more stuff in flatpak
- Use `flatpak-spawn --host` to execute things on the host.

**Comment by ricvelozo** [comment]
I think `--talk-name=org.freedesktop.Flatpak` is missing from manifest to be able to use `flatpak-spawn --host` in terminal, like in VS Code. I get the error:

```console
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by x80486** [comment]
I can add that one :sunglasses:

**Comment by x80486** [comment]
`--talk-name=org.freedesktop.Flatpak` added from release `2019.2` onwards

**Comment by tunix** [comment]
> You fix this by getting a job at JetBrains and spend months redesigning the core of the editor to understand commands executing in different environments.
> 
> In the mean time you either:
> 
>     * Package more stuff in flatpak
> 
>     * Use `flatpak-spawn --host` to execute things on the host.

I don't get this. Isn't this a flatpak packaging issue? How is this related to Jetbrains? I'm able to use the integrated terminal with the snap package for instance. (with classic confinement though) I'm kind of new to flatpak's so maybe I'm missing the point but is it not possible to allow execution of binaries in /bin while still benefiting from the sandbox?

**Comment by TingPing** [comment]
> I'm able to use the integrated terminal with the snap package for instance. (with classic confinement though) I'm kind of new to flatpak's so maybe I'm missing the point but is it not possible to allow execution of binaries in /bin while still benefiting from the sandbox?

It is not possible. That is why neither snap nor flatpak do it.

**Comment by tunix** [comment]
> > I'm able to use the integrated terminal with the snap package for instance. (with classic confinement though) I'm kind of new to flatpak's so maybe I'm missing the point but is it not possible to allow execution of binaries in /bin while still benefiting from the sandbox?
> 
> It is not possible. That is why neither snap nor flatpak do it.

What do you mean by not possible? I use IntelliJ Idea daily as a snap package. And I'm able to open up the embedded terminal, and perfectly able to execute other binaries installed on the system such as git, zsh. I have `git-flow` and `git-review` packages installed on my system and I'm able to execute them inside the embedded terminal.

**Comment by TingPing** [comment]
You said yourself the snap is unconfined. Flatpak simply is always confined.

**Comment by pdg-chargelab** [comment]
> You said yourself the snap is unconfined. Flatpak simply is always confined.

Hence, as @tunix pointed out, this is a packaging issue, not an issue with Intellij, and in no way requires Jetbrains to fix it.

**Comment by acuteaura** [comment]
The functionality of this package is so limited, it should either have a large disclaimer or be entirely unlisted from Flathub.

To everyone I've known to have installed it, or any other JetBrains IDE, it was merely a waste of time and bandwidth, because the features you'd install a heavy IDE for are entirely broken.

This is not just my opinion, read the reviews on these listings.

**Comment by ARehmanMahi** [comment]
Not sure if we are talking about what I think it is, but the following simply works, I can access my system's terminal.

![Screenshot from 2022-09-27 00-57-39](https://user-images.githubusercontent.com/3149876/192368336-0291c279-b1ff-48ef-bc58-9da4eaf76ad1.png)

**Comment by der-ali** [comment]
`flatpak-spawn  --host` is not working on  GoLand 2022.3.2

**Comment by der-ali** [comment]
Adding `org.freedesktop.Flatpak` to Session Bus resolved the issue.

**Comment by error-try-again** [comment]
> Please ignore if this is irrelevant, just wanted to share that the following works for me, I can access my system's terminal. The `shell path` settings `/usr/bin/flatpak-spawn --host --env=TERM=xterm-256color bash`
> 
> ![Screenshot from 2022-09-27 00-57-39](https://user-images.githubusercontent.com/3149876/192368336-0291c279-b1ff-48ef-bc58-9da4eaf76ad1.png)

This works, but it produces the following error:

**Comment by pgalbraith** [comment]
So long as Flatpak packagers think it's the application developer's responsibility to identify and fix Flatpak integration issues, or worse, that integration issues aren't really issues at all, then using any Flatpak packaged app is pretty much a waste of your time.  You are much better off getting the app from the developer's site and installing per their directions.

**Comment by NorbiPeti** [comment]
[host-spawn](https://github.com/1player/host-spawn) could be used to get full access to the host terminal. I think it's worth considering using that as the default and setting up Git & GPG to run outside the sandbox as well. There are too many things that can break in an IDE when sandboxed to make it worth it IMO but I love the simplicity of updating Flatpak apps. Although I also have issues running Java outside the sandbox as it complains about a `java.security` thing but that's another topic. I wonder if it's possible to somehow bridge the gaps better (I just ran into an issue where my app would require a lib from the host so I can't run it from the IDE to run tests).

**Comment by Rei-Nicolau-o-Grande** [comment]
i'm on linux mint and using zsh worked for me `/usr/bin/flatpak-spawn --host --env=TERM=xterm-256color zsh`

**Comment by jvalecillos** [comment]
I just discovered this issue while trying to use the "External Tool" settings to run a custom command using `docker` to spin up some dependencies before running my application. It cannot find the `docker` binary because there's no access to `/usr/bin/`. I tried to add such access using `Flatseal` as well as other suggestions here but nothing works.
