### ISSUE TITLE
2019.1.1 still not available via flatpak repository

### ISSUE THREAD

**Issue by Ravenow** [flathub/com.jetbrains.IntelliJ-IDEA-Community#15]
What is the way to install 2019.1.1 via flatpak?

Thanks.

**Comment by x80486** [comment]
I updated the manifest, but somehow it never made it; I'm waiting for version `2019.1.2` to come out to see if that one gets updated successfully.

**Comment by TingPing** [comment]
> I updated the manifest, but somehow it never made it; I'm waiting for version `2019.1.2` to come out to see if that one gets updated successfully.

Just trigger a new build...

Go here: https://flathub.org/builds
Login, Start build, type app-id (rest blank)

**Comment by x80486** [comment]
I triggered another build and this time went through:

```shell
[x80486@uplink ~]$ flatpak remote-info --log flathub com.jetbrains.IntelliJ-IDEA-Community

IntelliJ IDEA Community - Capable and Ergonomic Java IDE

        ID: com.jetbrains.IntelliJ-IDEA-Community
       Ref: app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 2019.1
   License: Apache-2.0
Collection: org.flathub.Stable
  Download: 585.7 MB
 Installed: 1.1 GB
   Runtime: org.freedesktop.Sdk/x86_64/18.08

       Sdk: org.freedesktop.Sdk/x86_64/18.08
    Commit: 2e436dcd0080e1752c6887a0d1294d09b298a05df451b527017dd86252bb8f83
    Parent: a5dedcf4b072a9b4288649be18b629cb3d4725dd4c76fedc391332a253826503
   Subject: intellij idea community edition release 2019.1.1 (106f9ef9)
      Date: 2019-05-04 19:47:19 +0000

...
```

@Ravenow, you should be able to update any time.
