### ISSUE TITLE
can't access ssh keys, proper shell, incorrect run with emulator  + symlinks to folders

### ISSUE THREAD

**Issue by mittwerk** [flathub/com.jetbrains.IntelliJ-IDEA-Community#164]
![image](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/assets/135833222/814ce470-61fd-427b-a7a6-71f1ef9045a9)
![image](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/assets/135833222/f546355a-d4b2-4ebf-907c-0aaee65ea9ad)
also there is a small problem with the emulator, it does not turn on the first time when I run build and also does not displaying symlinks to folders in the home directory, and yes it doesn't open access to fish shell, but by default instead of bash open term in sh

**Comment by x80486** [comment]
Git over SSH works fine in this Flatpak. You are just getting a typical error while authenticating with GitHub. I would suggest trying to sort this out in your terminal first.

I don't know what emulator is, but feel free to open up an issue with the details about the problem.

Shell access is a little bit tricky with these Flatpaks. Make sure you read through all the issues that have been opened in this regard, and if you are facing something different, feel free to open an issue with the specifics.
