### ISSUE TITLE
"The IDE seems to be launched with a script launcher" warning on start

### ISSUE THREAD

**Issue by Newbytee** [flathub/com.jetbrains.IntelliJ-IDEA-Community#177]
When I started IntelliJ IDEA Community for the first time, it gave me a warning stating that "The IDE seems to be launched with a script launcher ('bin/idea.sh'). Please consider switching to a native launcher ('bin/idea') for better experience":

![image](https://github.com/user-attachments/assets/835b21da-cfa2-45f2-bc99-1976247751cb)

I assume that is something this Flatpak package should resolve?

**Comment by x80486** [comment]
This started happening recently. Almost all JetBrains (Flatpak) applications are using a "wrapper" (https://github.com/Lctrs/jetbrains-flatpak-wrapper/) to start.

I don't have time right now to look at this, and everything is (still) working as usual, but I guess there should be a way to do everything (at startup) that the wrapper is providing, and just use the `bin/idea` native launcher in the end.
