### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mukulsharma9118** [flathub/com.jetbrains.IntelliJ-IDEA-Community#31]
Getting this error

**flatpak install flathub com.jetbrains.IntelliJ-IDEA-Community**
Looking for matches…

com.jetbrains.IntelliJ-IDEA-Community permissions:
    ipc     network     ssh-auth     wayland     x11     dri     file access [1]    dbus access [2]

    [1] host, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications, org.freedesktop.secrets

        ID                                               Branch            Op            Remote            Download
 1. [✗] com.jetbrains.IntelliJ-IDEA-Community            stable            i             flathub           1.0 kB / 671.2 MB

Error: While trying to checkout a31f5f42e8ddea472acb6433792e511760ed9cd8dbdbc204f71cc9a2e7da4b6b into /home/mukul/.local/share/flatpak/app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable/.a31f5f42e8ddea472acb6433792e511760ed9cd8dbdbc204f71cc9a2e7da4b6b-1A02G0: Opening content object 09cd50e6d0fd258795368ef20cddcddaf5a3667ddb86238245588571c5b1680e: Couldn't find file object '09cd50e6d0fd258795368ef20cddcddaf5a3667ddb86238245588571c5b1680e'
error: Failed to install com.jetbrains.IntelliJ-IDEA-Community: While trying to checkout a31f5f42e8ddea472acb6433792e511760ed9cd8dbdbc204f71cc9a2e7da4b6b into /home/mukul/.local/share/flatpak/app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable/.a31f5f42e8ddea472acb6433792e511760ed9cd8dbdbc204f71cc9a2e7da4b6b-1A02G0: Opening content object 09cd50e6d0fd258795368ef20cddcddaf5a3667ddb86238245588571c5b1680e: Couldn't find file object '09cd50e6d0fd258795368ef20cddcddaf5a3667ddb86238245588571c5b1680e'

**Comment by x80486** [comment]
I believe this should have been an issue with Flathub:

```shell
x80486@ubuntu-vm:~$ flatpak install flathub com.jetbrains.IntelliJ-IDEA-Community 
Looking for matches…

com.jetbrains.IntelliJ-IDEA-Community permissions:
    ipc                  network      ssh-auth      wayland      x11      dri      file access [1]
    dbus access [2]

    [1] host, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications, org.freedesktop.secrets

        ID                                               Arch              Branch            Remote             Download
 1. [✓] com.jetbrains.IntelliJ-IDEA-Community            x86_64            stable            flathub            321.2 MB / 671.2 MB

Installation complete.
```

**Comment by mukulsharma9118** [comment]
Still facing the same issue, Tried multiple times

**Comment by x80486** [comment]
I think you might be facing a network issue, or your system is in some kind of weird state. I would delete anything related with this package (be aware that it you have another JetBrains product they tend to share some directory structure).

The package is available, but as you can see, I couldn't install it the first time, but the second...that's OK, the network/server(s) some time fails:

![image](https://user-images.githubusercontent.com/34633617/77849933-37e85a80-719d-11ea-88bc-46a18ac41ce8.png)

**Comment by x80486** [comment]
@mukulsharma9118, are you still unable to install this package?
