### ISSUE TITLE
Ant builds not working

### ISSUE THREAD

**Issue by FrostyPenguin** [flathub/com.jetbrains.IntelliJ-IDEA-Community#33]
For me, trying to compile a project with Ant results in

```
Error: could not open `/run/host/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/jvm.cfg'
```
I'm using the bundled Ant version:
![](https://user-images.githubusercontent.com/29505577/77234889-0aeee300-6bb2-11ea-8cb8-485a8f423a3a.png)

**Steps to reproduce**

1. Create a simple Java project that uses a simple Ant script
2. Try to run an Ant task from the Ant menu on the right.

**Comment by x80486** [comment]
You are going to have these sort of unexpected results if you keep using that location for the Java SDK.

Have a look at issue `How to configure JDK in Intellij on Fedora Silverblue?` You will find several approaches on how to install and configure the Java SDK (or any other SDKs also).

**Comment by FrostyPenguin** [comment]
Hi, thanks for your quick response!

Actually, installing `flatpak install --system org.freedesktop.Sdk.Extension.openjdk8//19.08` partially solved this issue for me. However, I use Maven in my Ant script and IDEA still doesn't find the `mvn` binary.
Even if I'd install `mvn` somewhere in my home directory I highly doubt I'd be able to configure IDEA to add this path to the PATH variable.
I guess the only way that might work is creating an entirely new Flatpak extension for Maven and installing it.
![Screenshot from 2020-03-22 01-30-56](https://user-images.githubusercontent.com/29505577/77239600-cfb5d980-6bdc-11ea-86e2-248f3221d9ab.png)

Am I missing something obvious here?

**Comment by x80486** [comment]
I think for those cases, the bulletproof approach is to use the Takari's Maven wrapper, so you know that, no matter how you ship and configure your project, the script is able to run that command successfully all the time, downloading the pinned Maven version for the project.

In any case, if you want to use something "global", you can place the Maven installation in your `HOME` directory or use `asdf` (what I use) to install Maven. Also, IntelliJ IDEA bundles a Maven installation, but I wouldn't rely on it.

I have no idea if it's possible to create an Sdk extension for those build tools: `Maven`, `Gradle`, `rebar`, `Cargo`, etc.

**Comment by FrostyPenguin** [comment]
Thank you, again, for your quick reply!
I think I know the rough way from here. Installing Maven in my home directory sounds like a good solution to this problem.
I'll return here if I keep running into problems, but for now, I think I can close this issue.

Thanks for your fast help, and please feel free to reopen if you want to add something.
