### ISSUE TITLE
Sandboxing (and some other) Improvement(s)

### ISSUE THREAD

**Issue by x80486** [flathub/com.jetbrains.IntelliJ-IDEA-Community#45]
The main purpose of this enhancement is the improvement of sandboxing.

- Removing `host` access. IntelliJ will have default access to persist information only to `~/IdeaProjects` (and the default location used for the plugins, if they write outside the `xdg-*` sub-directories)
- Provide latest OpenJDK LTS (as Flatpak extension) for the IDE and embedded shell
- Removing `wayland` socket because IntelliJ doesn't support it yet — when running the Flatpak on wayland it will fallback to x-wayland)

**Comment by lightonflux** [comment]
Another one is `allow=devel` otherwise the debugger cannot access the process cause ptrace is blocked.
