### ISSUE TITLE
'Show in File Manager' stopped working

### ISSUE THREAD

**Issue by KevinAtSesam** [flathub/com.jetbrains.IntelliJ-IDEA-Community#46]
Think that with one of the later updates, the right-click menu option 'Show in Files Manager' stopped working. It doesn't give any console output, else I would have provided you some basic logging.

**Comment by x80486** [comment]
Hi @KevinAtSesam, I remember facing the same issue a while back, but the latest version doesn't have that problem anymore.

I've tested it under `Arch Linux` and `Ubuntu` (latest).
