### ISSUE TITLE
Request: Upgrade IntelliJ IDEA to Version 2020.3.2

### ISSUE THREAD

**Issue by byteshiva** [flathub/com.jetbrains.IntelliJ-IDEA-Community#54]
Can someone upgrade IntelliJ to 2020.3.2,

IntelliJ IDEA 2020.3.2 is available with the following bug fixes:

I see the below message while trying to update intelliJ

![image](https://user-images.githubusercontent.com/10637299/105872676-ab0e6780-6020-11eb-935c-6854b58b920a.png)

**Comment by x80486** [comment]
Done on #53 ...you need to wait for it to become available.

**Comment by byteshiva** [comment]
Thanks,
I'm able to upgrade from Flathub.

```
$ flatpak update 
Looking for updates…


        ID                                       Arch      Branch    Remote    Download
 1. [✓] com.jetbrains.IntelliJ-IDEA-Community    x86_64    stable    flathub   73.0 MB / 732.1 MB

Updates complete.

```
