### ISSUE TITLE
Is this a deterministic build from source or a wrapper on binaries?

### ISSUE THREAD

**Issue by geekley** [flathub/com.jetbrains.IntelliJ-IDEA-Community#56]
Hi, just a few questions...
1. Is the flatpak a deterministic build from https://github.com/JetBrains/intellij-community source code or is it just a wrapper on binaries compiled by Jetbrains?
2. Is this "more sandboxed" than the snap --classic version? Does sandboxnig affect features in any way?

**Comment by x80486** [comment]
If you take a look at the Flatpak manifest you can see it's not a build from that repo, but a wrapper a-la-Flatpak from the official build.

I can't tell much about `snap --classic` 🤷🏻‍♂️

There is Flathub forum also — you might get better answers there.

**Comment by geekley** [comment]
You mean the YAML file, right? I'm still a noob in this, so thanks for the answer.
