### ISSUE TITLE
Git commit fails with GPG

### ISSUE THREAD

**Issue by triceo** [flathub/com.jetbrains.IntelliJ-IDEA-Community#62]
When committing in Git with GPG support enabled (https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work), IntelliJ in Flatpak currently does not work:

   0 file committed, 1 file failed to commit: 
   gpg failed to sign the data failed to write commit object

This is an issue in Flatpak:
https://github.com/flatpak/flatpak/issues/2301

But there appears to be workaround:
https://github.com/flathub/org.gnu.emacs/pull/25

**Comment by x80486** [comment]
I'll try to put the same solution SmartGit is using and see how that goes. Build is currently failing due to some error with GCR 😠

**Comment by triceo** [comment]
@x80486 Mind trying again, please?

**Comment by x80486** [comment]
@triceo, double check if this works for you also. I never use this integration, but I just did a quick test using the GitHub token approach and it worked.

**Comment by triceo** [comment]
So if I pull from Flatpak, I will get the fix now? If so, I will check it next week, I am (technically) off work this week.
