### ISSUE TITLE
Review the possibility of adding aditional documentation about permissions

### ISSUE THREAD

**Issue by 0xalen** [flathub/com.jetbrains.IntelliJ-IDEA-Community#66]
**Situation**

Whej one installs IntelliJ IDEA Community from flathub there's a section requiring the following permission:
```
com.jetbrains.IntelliJ-IDEA-Community permissions:
    ipc       network       ssh-auth              wayland
    x11       dri           file access [1]       dbus access [2]

    [1] host, xdg-run/gnupg:ro, xdg-run/keyring
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets, org.gnome.keyring.SystemPrompter
```
**Problem**
I'd like to understand why such permissions are asked, but after going through the code, searching for it on forums, etc. I've not been able to find any explanation as to why does it require access to gnome-keyring o ssh-auth, for instance.

**Request**
It would be very helpful if there was a paragraph or a link to another resource in which one could find such information.

P.S: Thank you for putting the work into maintaining this flatpak.

**Comment by x80486** [comment]
There is a `Git` plugin, and some users access their repositories via SSH, hence the reason for those `ssh-auth` and `gnome-keyring`.
