### ISSUE TITLE
Integration with external tools not working

### ISSUE THREAD

**Issue by pdg-chargelab** [flathub/com.jetbrains.IntelliJ-IDEA-Community#67]
I'm brand new to flatpak so I don't know how hard or easy this would be to fix on my own.  I find that the flatpak packaging doesn't allow me to integrate with external tools (e.g. browsers like Chrome/Firefox, or diff/merge tools like Beyond Compare).  I'm using the snap package instead in the meantime, which allows me to use those tools with Intellij Idea.

**Comment by pdg-chargelab** [comment]
I guess this is really the same as #14?

**Comment by x80486** [comment]
@pdg-chargelab, Flatpak is always sandboxed, so this tends to cause some troubles for any software that does not provide the means to be integrated in such ways. There is a way to make this work out-of-the-box by using `flatpak-spawn --host /path/to/command`, some times this is not possible, hence you would need a proper integration done by the software owners.

That's not  super-technical, but it's how I understand it.

**Comment by pdg-chargelab** [comment]
If you're suggesting that JetBrains (or Google) should be responsible for
specifically developing their applications such that they integrate in
Flatpak sandbox environments (and, presumably every other packaging scheme
that comes along as well), I completely disagree with that line of
reasoning.  It's the packagers job to package the application so it works,
as it is, not so that it only works if the developer changes it to suit the
packagers preferences.
