### ISSUE TITLE
Cannot attach to a running process

### ISSUE THREAD

**Issue by essembeh** [flathub/com.jetbrains.IntelliJ-IDEA-Community#69]
Hi

I've been using IDEA-Community for a while and recently gave a try to the flatpak version: com.jetbrains.IntelliJ-IDEA-Community

I noticed the I cannot attach to a running Tomcat server, the process is not shown in the dialog via "Run" -> "Attach to Process"
I usually run a custom tomcat webserver which is not in a sandbox and attach it from IntelliJ, but maybe the flatpak apps being sandboxed, they cannot access other PID?

I tried to play with permissions using Flatseal but couldn't make it work.
Is there a solution to attach to process not from the sandbox?

Thanks

**Comment by x80486** [comment]
Let me check if there is an easy/sane way. I know exactly what you are trying to do.

How do you "install" Tomcat? Unpack and use in your `home`?

**Comment by x80486** [comment]
I was unable to connect to either, even starting Tomcat within the IDEA's terminal 😭

On the other hand you can achieve the same (or very similar) by using this plugin: https://plugins.jetbrains.com/plugin/8266-tomcat-runner/ with your existing Tomcat "installation" 😀 — I tried it without modifying any configuration/settings in Tomcat (just download and unpack).

Once you have the plugin installed you would need to create a `Run/Debug` configuration, select `Tomcat` (type), fill any of the VM or environment arguments (if needed)...and then just use it, toggling between `Run` and `Debug` without modifying anything :)

**Comment by essembeh** [comment]
Sorry for the delay.
I'll give a try to a dedicated plugin to run tomcat on monday.
I'm pretty sure too that since tomcat will be launched by intellij, there won't be any problem to attach the process.

Thanks for the hint.

**Comment by x80486** [comment]
@essembeh, I'll close this one for the time being. Feel free to reopen it if you are still facing the issue.
